name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual publish)'
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Typecheck
        run: bun run typecheck
        
      - name: Lint
        run: bun run lint
      
      - name: Build
        run: bun run build
      
      - name: Create GitHub Release
        if: ${{ !inputs.dry_run && github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
      
      - name: Dry Run - Skip GitHub Release
        if: ${{ inputs.dry_run || github.event_name == 'workflow_dispatch' }}
        run: echo "SKIPPING GITHUB RELEASE in dry run mode"
      
      - name: Publish to npm
        if: ${{ !inputs.dry_run && github.event_name == 'push' }}
        run: bunx npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Dry Run - Simulate npm Publish
        if: ${{ inputs.dry_run || github.event_name == 'workflow_dispatch' }}
        run: |
          echo "DRY RUN: Would publish package to npm"
          bunx npm publish --dry-run
